// ============================================================
// Seed data para demo - 20 productos, 8 proveedores, lotes
// ============================================================
import {
  Comprador,
  Proveedor,
  Producto,
  Lote,
  Orden,
} from '@/types';

export const COMPRADORES: Comprador[] = [
  {
    id: 'buyer-1',
    nombre: 'Cafetería El Rincón',
    tipo_local: 'cafeteria',
    zona: 'Palermo',
    direccion: 'Thames 1234, CABA',
    lat: -34.591,
    lng: -58.433,
    productos_frecuentes: ['prod-1', 'prod-2', 'prod-6', 'prod-11'],
  },
  {
    id: 'buyer-2',
    nombre: 'Restaurante La Esquina',
    tipo_local: 'restaurante',
    zona: 'San Telmo',
    direccion: 'Defensa 890, CABA',
    lat: -34.619,
    lng: -58.371,
    productos_frecuentes: ['prod-7', 'prod-8', 'prod-9', 'prod-3'],
  },
];

export const PROVEEDORES: Proveedor[] = [
  {
    id: 'prov-1',
    nombre: 'Panadería Don Agustín',
    tipo: 'panaderia',
    zona: 'Villa Crespo',
    direccion: 'Corrientes 4500, CABA',
    lat: -34.601,
    lng: -58.441,
    categorias: ['panificados'],
    rating: 4.8,
    entrega: true,
  },
  {
    id: 'prov-2',
    nombre: 'Lácteos del Valle',
    tipo: 'productor',
    zona: 'Mataderos',
    direccion: 'Av. Larrazábal 2100, CABA',
    lat: -34.667,
    lng: -58.506,
    categorias: ['lacteos'],
    rating: 4.5,
    entrega: true,
  },
  {
    id: 'prov-3',
    nombre: 'Verduras Frescas SA',
    tipo: 'mayorista',
    zona: 'Mercado Central',
    direccion: 'Autopista Riccheri km 35',
    lat: -34.706,
    lng: -58.546,
    categorias: ['frescos_verdura'],
    rating: 4.2,
    entrega: false,
  },
  {
    id: 'prov-4',
    nombre: 'Frigorífico El Gaucho',
    tipo: 'distribuidor',
    zona: 'Liniers',
    direccion: 'Av. Rivadavia 11200, CABA',
    lat: -34.647,
    lng: -58.523,
    categorias: ['frescos_carne', 'congelados'],
    rating: 4.6,
    entrega: true,
  },
  {
    id: 'prov-5',
    nombre: 'Bebidas Mayoreo',
    tipo: 'distribuidor',
    zona: 'Avellaneda',
    direccion: 'Mitre 890, Avellaneda',
    lat: -34.666,
    lng: -58.367,
    categorias: ['bebidas'],
    rating: 4.3,
    entrega: true,
  },
  {
    id: 'prov-6',
    nombre: 'Café Premium Import',
    tipo: 'mayorista',
    zona: 'Palermo',
    direccion: 'Av. Santa Fe 3800, CABA',
    lat: -34.588,
    lng: -58.424,
    categorias: ['cafe_infusiones'],
    rating: 4.9,
    entrega: true,
  },
  {
    id: 'prov-7',
    nombre: 'Descartables Express',
    tipo: 'distribuidor',
    zona: 'Floresta',
    direccion: 'Av. Rivadavia 8900, CABA',
    lat: -34.629,
    lng: -58.479,
    categorias: ['descartables', 'limpieza'],
    rating: 4.0,
    entrega: true,
  },
  {
    id: 'prov-8',
    nombre: 'Molinera San Martín',
    tipo: 'fabrica',
    zona: 'La Matanza',
    direccion: 'Ruta 3 km 28, La Matanza',
    lat: -34.679,
    lng: -58.612,
    categorias: ['secos', 'panificados'],
    rating: 4.4,
    entrega: true,
  },
];

export const PRODUCTOS: Producto[] = [
  // Panificados
  { id: 'prod-1', categoria: 'panificados', nombre: 'Medialunas', unidad: 'unidad', descripcion: 'Medialunas de manteca, tamaño estándar' },
  { id: 'prod-2', categoria: 'panificados', nombre: 'Facturas surtidas', unidad: 'unidad', descripcion: 'Surtido de facturas de manteca' },
  { id: 'prod-3', categoria: 'panificados', nombre: 'Pan de mesa', unidad: 'kg', descripcion: 'Pan francés o ladrillo' },
  { id: 'prod-4', categoria: 'secos', nombre: 'Harina 000', unidad: 'kg', descripcion: 'Harina de trigo triple cero' },
  { id: 'prod-5', categoria: 'secos', nombre: 'Harina 0000', unidad: 'kg', descripcion: 'Harina de trigo cuatro ceros para pastelería' },
  // Lácteos
  { id: 'prod-6', categoria: 'lacteos', nombre: 'Queso crema', unidad: 'kg', descripcion: 'Queso crema tipo Philadelphia' },
  { id: 'prod-7', categoria: 'lacteos', nombre: 'Queso en barra', unidad: 'kg', descripcion: 'Queso cuartirolo o mozzarella' },
  { id: 'prod-8', categoria: 'lacteos', nombre: 'Leche entera', unidad: 'litro', descripcion: 'Leche entera pasteurizada' },
  { id: 'prod-9', categoria: 'lacteos', nombre: 'Manteca', unidad: 'kg', descripcion: 'Manteca sin sal' },
  // Frescos
  { id: 'prod-10', categoria: 'frescos_verdura', nombre: 'Tomate perita', unidad: 'kg', descripcion: 'Tomate perita de primera calidad' },
  { id: 'prod-11', categoria: 'frescos_verdura', nombre: 'Cebolla blanca', unidad: 'kg', descripcion: 'Cebolla blanca categoría A' },
  { id: 'prod-12', categoria: 'frescos_verdura', nombre: 'Lechuga', unidad: 'unidad', descripcion: 'Lechuga mantecosa o criolla' },
  { id: 'prod-13', categoria: 'frescos_carne', nombre: 'Pollo entero', unidad: 'kg', descripcion: 'Pollo entero frío sin menudos' },
  { id: 'prod-14', categoria: 'frescos_carne', nombre: 'Nalga vacuna', unidad: 'kg', descripcion: 'Nalga de primera para fiambres o asado' },
  // Bebidas
  { id: 'prod-15', categoria: 'bebidas', nombre: 'Agua mineral x12', unidad: 'caja', descripcion: 'Agua mineral 500ml, 12 unidades' },
  { id: 'prod-16', categoria: 'bebidas', nombre: 'Gaseosa 2.5L x6', unidad: 'pack', descripcion: 'Gaseosas variadas 2.5L, pack de 6' },
  // Café
  { id: 'prod-17', categoria: 'cafe_infusiones', nombre: 'Café molido premium', unidad: 'kg', descripcion: 'Mezcla especial para espresso' },
  { id: 'prod-18', categoria: 'cafe_infusiones', nombre: 'Té surtido x100', unidad: 'caja', descripcion: 'Caja 100 saquitos variados' },
  // Descartables
  { id: 'prod-19', categoria: 'descartables', nombre: 'Vasos descartables x100', unidad: 'pack', descripcion: 'Vasos plásticos 200ml, pack 100' },
  { id: 'prod-20', categoria: 'descartables', nombre: 'Servilletas x500', unidad: 'pack', descripcion: 'Servilletas de papel blancas' },
];

// Lotes disponibles - mix de stock normal y excedentes
export const LOTES: Lote[] = [
  {
    id: 'lote-1',
    supplier_id: 'prov-1',
    product_id: 'prod-1',
    cantidad: 500,
    precio_unitario: 350,
    compra_minima: 50,
    vencimiento: '2026-06-08',
    urgencia: 'urgente',
    descripcion: '⚡ Excedente de producción de hoy. Precio especial por rotación rápida.',
    activo: true,
  },
  {
    id: 'lote-2',
    supplier_id: 'prov-1',
    product_id: 'prod-2',
    cantidad: 300,
    precio_unitario: 280,
    compra_minima: 30,
    urgencia: 'normal',
    descripcion: 'Facturas surtidas frescas, producción diaria.',
    activo: true,
  },
  {
    id: 'lote-3',
    supplier_id: 'prov-1',
    product_id: 'prod-3',
    cantidad: 200,
    precio_unitario: 1200,
    compra_minima: 10,
    urgencia: 'normal',
    descripcion: 'Pan de mesa, entrega antes de las 8am.',
    activo: true,
  },
  {
    id: 'lote-4',
    supplier_id: 'prov-2',
    product_id: 'prod-6',
    cantidad: 80,
    precio_unitario: 4800,
    compra_minima: 5,
    vencimiento: '2026-06-15',
    urgencia: 'excedente',
    descripcion: '🏷️ Lote excedente: 20% de descuento vs precio habitual.',
    activo: true,
  },
  {
    id: 'lote-5',
    supplier_id: 'prov-2',
    product_id: 'prod-7',
    cantidad: 150,
    precio_unitario: 6200,
    compra_minima: 5,
    urgencia: 'normal',
    descripcion: 'Queso en barra cuartirolo, entrega refrigerada.',
    activo: true,
  },
  {
    id: 'lote-6',
    supplier_id: 'prov-2',
    product_id: 'prod-9',
    cantidad: 100,
    precio_unitario: 5500,
    compra_minima: 5,
    urgencia: 'normal',
    descripcion: 'Manteca sin sal, bloque 1kg.',
    activo: true,
  },
  {
    id: 'lote-7',
    supplier_id: 'prov-3',
    product_id: 'prod-10',
    cantidad: 500,
    precio_unitario: 980,
    compra_minima: 20,
    vencimiento: '2026-06-10',
    urgencia: 'urgente',
    descripcion: '⚡ Tomate perita cosecha de ayer. Precio mayorista. Retiro en Mercado Central.',
    activo: true,
  },
  {
    id: 'lote-8',
    supplier_id: 'prov-3',
    product_id: 'prod-11',
    cantidad: 400,
    precio_unitario: 420,
    compra_minima: 20,
    urgencia: 'normal',
    descripcion: 'Cebolla blanca categoría A, bolsa 20kg.',
    activo: true,
  },
  {
    id: 'lote-9',
    supplier_id: 'prov-4',
    product_id: 'prod-13',
    cantidad: 300,
    precio_unitario: 3200,
    compra_minima: 10,
    urgencia: 'normal',
    descripcion: 'Pollo entero frío. Entrega en camión refrigerado.',
    activo: true,
  },
  {
    id: 'lote-10',
    supplier_id: 'prov-4',
    product_id: 'prod-14',
    cantidad: 150,
    precio_unitario: 7800,
    compra_minima: 5,
    urgencia: 'excedente',
    descripcion: '🏷️ Nalga vacuna, lote excedente de cancelación. Entrega inmediata.',
    activo: true,
  },
  {
    id: 'lote-11',
    supplier_id: 'prov-5',
    product_id: 'prod-15',
    cantidad: 200,
    precio_unitario: 1800,
    compra_minima: 10,
    urgencia: 'normal',
    descripcion: 'Agua mineral 500ml x12, marca premium.',
    activo: true,
  },
  {
    id: 'lote-12',
    supplier_id: 'prov-5',
    product_id: 'prod-16',
    cantidad: 120,
    precio_unitario: 3400,
    compra_minima: 6,
    urgencia: 'normal',
    descripcion: 'Gaseosas 2.5L variadas, pack x6.',
    activo: true,
  },
  {
    id: 'lote-13',
    supplier_id: 'prov-6',
    product_id: 'prod-17',
    cantidad: 50,
    precio_unitario: 12500,
    compra_minima: 2,
    urgencia: 'normal',
    descripcion: 'Café molido mezcla especial para espresso. Tueste medio-oscuro.',
    activo: true,
  },
  {
    id: 'lote-14',
    supplier_id: 'prov-6',
    product_id: 'prod-18',
    cantidad: 100,
    precio_unitario: 2200,
    compra_minima: 5,
    urgencia: 'excedente',
    descripcion: '🏷️ Té surtido importado, lote de temporada. Precio liquidación.',
    activo: true,
  },
  {
    id: 'lote-15',
    supplier_id: 'prov-7',
    product_id: 'prod-19',
    cantidad: 300,
    precio_unitario: 1100,
    compra_minima: 10,
    urgencia: 'normal',
    descripcion: 'Vasos descartables 200ml x100 unidades.',
    activo: true,
  },
  {
    id: 'lote-16',
    supplier_id: 'prov-7',
    product_id: 'prod-20',
    cantidad: 500,
    precio_unitario: 650,
    compra_minima: 20,
    urgencia: 'excedente',
    descripcion: '🏷️ Servilletas blancas x500. Sobrestock. Mejor precio del mercado.',
    activo: true,
  },
  {
    id: 'lote-17',
    supplier_id: 'prov-8',
    product_id: 'prod-4',
    cantidad: 2000,
    precio_unitario: 380,
    compra_minima: 50,
    urgencia: 'normal',
    descripcion: 'Harina 000 para panificación. Bolsas 1kg, caja x50.',
    activo: true,
  },
  {
    id: 'lote-18',
    supplier_id: 'prov-8',
    product_id: 'prod-5',
    cantidad: 1000,
    precio_unitario: 420,
    compra_minima: 25,
    urgencia: 'normal',
    descripcion: 'Harina 0000 para pastelería. Ideal para facturas y medialunas.',
    activo: true,
  },
];

// Órdenes de ejemplo para dashboard
export const ORDENES_DEMO: Orden[] = [
  {
    id: 'orden-demo-0',
    buyer_id: 'buyer-1',
    estado: 'entregada',
    items: [
      {
        lote_id: 'lote-3',
        producto_nombre: 'Pan de mesa',
        cantidad: 20,
        precio_unitario: 1200,
        subtotal: 24000,
        proveedor_nombre: 'Panadería Don Agustín',
      },
      {
        lote_id: 'lote-8',
        producto_nombre: 'Cebolla blanca',
        cantidad: 25,
        precio_unitario: 420,
        subtotal: 10500,
        proveedor_nombre: 'Verduras Frescas SA',
      },
    ],
    total: 34500,
    fecha_entrega: '2026-05-18',
    notas: 'Reposición de apertura de semana',
    created_at: '2026-05-17T09:00:00.000Z',
  },
  {
    id: 'orden-demo-1',
    buyer_id: 'buyer-1',
    estado: 'confirmada',
    items: [
      {
        lote_id: 'lote-1',
        producto_nombre: 'Medialunas',
        cantidad: 100,
        precio_unitario: 350,
        subtotal: 35000,
        proveedor_nombre: 'Panadería Don Agustín',
      },
      {
        lote_id: 'lote-4',
        producto_nombre: 'Queso crema',
        cantidad: 8,
        precio_unitario: 4800,
        subtotal: 38400,
        proveedor_nombre: 'Lácteos del Valle',
      },
    ],
    total: 73400,
    fecha_entrega: '2026-06-06',
    notas: 'Entrega antes de las 7am',
    created_at: '2026-06-05T08:30:00.000Z',
  },
  {
    id: 'orden-demo-2',
    buyer_id: 'buyer-1',
    estado: 'entregada',
    items: [
      {
        lote_id: 'lote-1',
        producto_nombre: 'Medialunas',
        cantidad: 120,
        precio_unitario: 350,
        subtotal: 42000,
        proveedor_nombre: 'Panadería Don Agustín',
      },
      {
        lote_id: 'lote-13',
        producto_nombre: 'Café molido premium',
        cantidad: 3,
        precio_unitario: 12500,
        subtotal: 37500,
        proveedor_nombre: 'Café Premium Import',
      },
    ],
    total: 79500,
    fecha_entrega: '2026-05-28',
    notas: 'Compra típica de fin de semana',
    created_at: '2026-05-27T11:15:00.000Z',
  },
  {
    id: 'orden-demo-3',
    buyer_id: 'buyer-1',
    estado: 'entregada',
    items: [
      {
        lote_id: 'lote-4',
        producto_nombre: 'Queso crema',
        cantidad: 10,
        precio_unitario: 4800,
        subtotal: 48000,
        proveedor_nombre: 'Lácteos del Valle',
      },
      {
        lote_id: 'lote-8',
        producto_nombre: 'Cebolla blanca',
        cantidad: 20,
        precio_unitario: 420,
        subtotal: 8400,
        proveedor_nombre: 'Verduras Frescas SA',
      },
    ],
    total: 56400,
    fecha_entrega: '2026-05-24',
    notas: 'Recompra de insumos de cocina',
    created_at: '2026-05-23T07:45:00.000Z',
  },
  {
    id: 'orden-demo-4',
    buyer_id: 'buyer-1',
    estado: 'entregada',
    items: [
      {
        lote_id: 'lote-2',
        producto_nombre: 'Facturas surtidas',
        cantidad: 60,
        precio_unitario: 280,
        subtotal: 16800,
        proveedor_nombre: 'Panadería Don Agustín',
      },
      {
        lote_id: 'lote-13',
        producto_nombre: 'Café molido premium',
        cantidad: 2,
        precio_unitario: 12500,
        subtotal: 25000,
        proveedor_nombre: 'Café Premium Import',
      },
      {
        lote_id: 'lote-15',
        producto_nombre: 'Vasos descartables x100',
        cantidad: 10,
        precio_unitario: 1100,
        subtotal: 11000,
        proveedor_nombre: 'Descartables Express',
      },
    ],
    total: 52800,
    fecha_entrega: '2026-05-21',
    created_at: '2026-05-20T10:20:00.000Z',
  },
  {
    id: 'orden-demo-5',
    buyer_id: 'buyer-2',
    estado: 'entregada',
    items: [
      {
        lote_id: 'lote-5',
        producto_nombre: 'Queso en barra',
        cantidad: 15,
        precio_unitario: 6200,
        subtotal: 93000,
        proveedor_nombre: 'Lácteos del Valle',
      },
      {
        lote_id: 'lote-10',
        producto_nombre: 'Nalga vacuna',
        cantidad: 8,
        precio_unitario: 7800,
        subtotal: 62400,
        proveedor_nombre: 'Frigorífico El Gaucho',
      },
    ],
    total: 155400,
    fecha_entrega: '2026-05-30',
    created_at: '2026-05-29T13:10:00.000Z',
  },
];

// Helpers de lookup
export function getProducto(id: string): Producto | undefined {
  return PRODUCTOS.find((p) => p.id === id);
}

export function getProveedor(id: string): Proveedor | undefined {
  return PROVEEDORES.find((p) => p.id === id);
}

export function getLotesConDetalle(): Lote[] {
  return LOTES.map((lote) => ({
    ...lote,
    producto: getProducto(lote.product_id),
    proveedor: getProveedor(lote.supplier_id),
  }));
}

// Calcular distancia ficticia (demo) en km desde zona buyer
export function calcularDistanciaDemo(zona_proveedor: string, zona_buyer: string): number {
  const mapa: Record<string, number> = {
    Palermo: 0,
    'Villa Crespo': 3,
    'San Telmo': 7,
    Mataderos: 12,
    'Mercado Central': 30,
    Liniers: 14,
    Avellaneda: 10,
    Floresta: 11,
    'La Matanza': 28,
  };
  const dist_a = mapa[zona_proveedor] ?? 15;
  const dist_b = mapa[zona_buyer] ?? 5;
  return Math.abs(dist_a - dist_b) + Math.floor(Math.random() * 3);
}
